reverse proxy support (#310)
* add reverse proxy support

This change involves several parts:

- replace absolute paths with relative ones
- use the referer to figure out the hostname, if behind a reverse proxy
- if no referer is available in a reverse proxy setup, use another workaround to create the proper /me link

* fix TypeError: res.sendStatus is not a function

* remove commented out debug code

* change form action back as per request

* resolve conflicts

* make future changes to the  link easier

* fix eslint issues

* improve code path

* eslint: ignore unused vars for arguments

* fix console error on main page where there is no me link